# NEO4J AUTH
neo4j_user = 'ENTER YOUR USERNAME'
neo4j_password = "ENTER YOUR PASSWORD"

# RDBMS AUTH
POSTGRES_DBNAME = "postgres"
POSTGRES_USER = "ENTER YOUR USERNAME"
POSTGRES_PASSWORD = "ENTER YOUR PASSWORD"
POSTGRES_HOST = "localhost"
POSTGRES_PORT = 5432

# MONGO AUTH
mongo_host = 'localhost'
mongo_port = 27017
